language: python
python:
  - "3.7"

env:
  - ENV=test NEO4J_AUTH=neo4j/test

install:
  - pip install -r requirements.txt

services:
  - neo4j
    ports:
      - 7687:7687
      - 7474:7474


script:
  - pytest -v src/tests